
SELECT SUM(SALARY) FROM CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS;
SELECT AVG(SALARY) FROM CUSTOMERS;
SELECT NAME, MIN(SALARY) FROM CUSTOMERS;
SELECT NAME, MAX(SALARY) FROM CUSTOMERS;

SELECT COUNT(*) FROM CUSTOMERS WHERE AGE > 10;
SELECT COUNT(*) FROM CUSTOMERS WHERE AGE < 10;
SELECT COUNT(*) FROM CUSTOMERS WHERE AGE BETWEEN 10 AND 30;
