-- SELECT column1, column2 ... columnN

-- FROM table_name AS alias_name

-- WHERE condition;
CREATE TABLE ORDERS (
  ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  DATE VARCHAR(20),
  CUSTOMER_ID INT, 
  AMOUNT INT,
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

INSERT INTO ORDERS(DATE, CUSTOMER_ID, AMOUNT) VALUES('2020-01-01', 6, 100);
INSERT INTO ORDERS(DATE, CUSTOMER_ID, AMOUNT) VALUES('2020-01-02', 7, 200);

SELECT C.ID, C.NAME, C.AGE, O.AMOUNT
FROM CUSTOMERS AS C, ORDERS AS O
WHERE C.ID = O.CUSTOMER_ID;

-- COLUMN ALIAS

SELECT  ID AS CUSTOMER_ID, NAME AS CUSTOMER_NAME
FROM CUSTOMERS
WHERE SALARY > 40000.00